# PYTHON3.9
# DJANGO 4.0.4
# PostgreSQL 14.3
version: "3.9"

# Running Python3.9 in a container
python:
  image: python:latest
  command: "sh -c 'pip install -r requirements.txt && python script.py'"
  volumes:
    - .:/app
