# PYTHON3.9
# DJANGO 4.0.4
# PostgreSQL 14.3

version: "3.9"

FROM: python:3.9.13-alpine
MAINTAINER: dockerAARHUS TECH Skoleoplaering

ENV: PYTHONUNBUFFERED

COPY: ./requirements.txt /requirements.txt # Copy the req file
RUN: pip install -r /requirements.txt # and install it into out Docker

services:
    database:
        container_name: postgres
        image: postgres14.3-alpine
        enviroment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_DB=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "${POSTGRES_PORT}:5432"                   #default PostgreSQL port
        

# NGINX