# PYTHON3.9
# DJANGO 4.0.4
# PostgreSQL 14.3

version: "3.9"

FROM: python:3.9.13-alpine
MAINTAINER: dockerAARHUS TECH Skoleoplaering

ENV: PYTHONUNBUFFERED

COPY: ./requirements.txt /requirements.txt # Copy the req file
RUN: pip install -r /requirements.txt # and install it into out Docker

RUN mkdir